figures :
	inkscape cloudarray_layers.svg -e cloudarray_layers.png -d 120
	inkscape cloudarraybox.svg -e cloudarraybox.png -d 60
	inkscape cloudarray_overview.svg -e cloudarray_overview.png -d 80
	inkscape gsd-logo.svg -e gsd-logo.png -d 80
#clean :
#	rm -f ${filename}.{eps,ps,pdf,log,aux,out,dvi,bbl,blg,lof,gls,ilg,ist,glo,toc} *~ *.log

