#!/bin/bash

###=============================================================================
#
#          FILE: CloudArray cleaner
# 
#         USAGE: ./cloudarraycleaner &
# 
#   DESCRIPTION: It kills unused containers by Infra.jl
# 
#       OPTIONS: ---
#  DEPENDENCIES: Docker
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Raphael P. Ribeiro
#  ORGANIZATION: GSD-UFAL
#       CREATED: 2016-07-07 03:31
###=============================================================================

# DISCLAIMER: based on examples from:
# 	https://github.com/JuliaWeb/HttpServer.jl/tree/master/examples

dockerList=($(docker ps -qa))
rmList=()

function isWorker()
{
        if [ $(docker exec $1 ps aux | grep -ic "julia") -ne 0 ]; then
                echo "true"
        else
                echo "false"
        fi
}

while :
do
        for cid in ${dockerList[@]}; do
                if [ "$(isWorker $cid)" == false ]; then
                        rmList+=($cid)
                fi
        done

        if [ -n "$rmList" ]; then
                docker rm --force ${rmList[@]}
        fi
        sleep 600 # wait 10 minutes to run again
done
